spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:mem:freesia  # IN-MEMORY
    url: jdbc:h2:tcp://localhost/~/freesia # TCP
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        format_sql: true # 실행되는 Query 를 보여줌.
        use_sql_comments: true # JPQL 확인 시 사용.
logging:
  level:
    org:
      hibernate:
        SQL: debug